### ISSUE TITLE
Update JupyterBook version and add MySTjs extension

### ISSUE THREAD

**Issue by tsnow03** [CryoInTheCloud/hub-image#39]
Need to add the new release of the JupyterBook package ([v0.13.1](https://github.com/executablebooks/jupyter-book)) and add the (MySTjs extension)[https://github.com/executablebooks/mystjs] to add functionality in building the JupyterBook.

**Comment by fperez** [comment]
JBook is now at [0.13.2](https://anaconda.org/conda-forge/jupyter-book). We should also add the new [jupyterlab-mystjs](https://anaconda.org/conda-forge/jupyter-book) extension, which I'm testing and is awesome.  It will make for a much better user experience with the MyST tools.

**Comment by weiji14** [comment]
We should already be at jupyter-book=0.13.1 according to https://github.com/CryoInTheCloud/hub-image/blame/3ebc676ae1af0b9a412792544bc47e3786761ae1/conda-linux-64.lock#L542, but I can add in [jupyterlab-myst](https://github.com/conda-forge/jupyterlab-myst-feedstock).

**Comment by fperez** [comment]
Awesome, many thanks @weiji14! A quick note that, myst is advancing very rapidly, and for at least a little while this means we'll need to do some rather frequent updates. But I hope the image update workflow is smooth enough that we can do so with minimal effort (I'm doing the same in my Berkeley teaching hub and it's not bad). I think the benefit is worth the effort, in order to help advance a modern publishing/comms tool that will serve us well in the long run.

cc @rowanc1 - this hub is a NASA-funded, 2i2c-run hub for the cryosphere community. Continuing to grow our base of testing users!

**Comment by rowanc1** [comment]
So cool! Please feel free to ping me @tsnow03 or @weiji14 if you need any help and open issues as you come across them! We will aim to fix things up as fast as we can.

The 1.1.0 release of jupyterlab-myst that you installed has the interactive inline execution in it (`` {eval}`1+1` ``), which works really well, but still needs a lot of tweaks to get right. See this [thread](https://twitter.com/rowancockett/status/1627793811169771520) for some screenshots. Madly working on improving the docs right now for this before the notebook format meeting next week!

**Comment by weiji14** [comment]
Cool, I'm definitely keeping an eye on jupyterlab-myst! Will need to find a cool project to use this on soon :smile:
